{
  "name": "retention",
  "compatibilityLevel": 1601,
  "model": {
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "dim_constants_research",
        "description": [
          "Figures taken from other data analysis reports",
          "Source file: dim_constants_research.csv"
        ],
        "lineageTag": "12dcbe1e-7af7-4370-93b9-a8ef0c2ef3ae",
        "columns": [
          {
            "name": "ConstantID",
            "dataType": "string",
            "sourceColumn": "ConstantID",
            "lineageTag": "dc8a7d7a-ada8-45a6-bad1-7673de3e9e13",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ConstantName",
            "dataType": "string",
            "sourceColumn": "ConstantName",
            "lineageTag": "d08de73d-bf27-403c-a995-3845108d634e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "lineageTag": "7d0414ba-f82c-4207-af61-fa96a525c975",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DisplayValue",
            "dataType": "double",
            "sourceColumn": "DisplayValue",
            "formatString": "0%;-0%;0%",
            "lineageTag": "4be2b8ae-c623-4e1b-953e-c64ce02cf049",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "d4aed2fc-8a26-449c-a96e-87510922803a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GeographicScope",
            "dataType": "string",
            "sourceColumn": "GeographicScope",
            "lineageTag": "06546f49-bac2-4caa-8efb-4e59f4442565",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Source",
            "dataType": "string",
            "sourceColumn": "Source",
            "lineageTag": "2a5b4b32-af39-46e5-8236-9c493ed5536f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "1dd750cf-11ec-438f-b19e-0957527effc0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LastUpdated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated",
            "formatString": "Long Date",
            "lineageTag": "7da2a6f7-728e-4eb0-bf00-83a3a8b26d94",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "976085ed-132c-4001-b99f-2a20c9eee21d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_774bd4c9-8f83-4a3f-9b7f-3b1b1b93112d",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Reliability",
            "dataType": "string",
            "sourceColumn": "Reliability",
            "lineageTag": "3358fd03-2318-46ca-a577-aca72360b9ef",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Notes",
            "dataType": "string",
            "sourceColumn": "Notes",
            "lineageTag": "223540e0-34a3-4bf7-9b9f-d196aee50f82",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_constants_research",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\my power bi\\aarhus-retention-model\\data\\processed\\dim_constants_research.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ConstantID\", type text}, {\"ConstantName\", type text}, {\"Value\", type number}, {\"DisplayValue\", Percentage.Type}, {\"Category\", type text}, {\"GeographicScope\", type text}, {\"Source\", type text}, {\"Description\", type text}, {\"LastUpdated\", type date}, {\"Reliability\", type text}, {\"Notes\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_5ab60a62-9f17-4e40-a620-8b2d85712185",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a47705d3-7455-4345-9550-7e57940c36ee",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "949d36ce-7355-487e-a682-625b053b40a4",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "b10ab307-36b9-43b3-83a7-1dfa5e93d20e",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "c825124e-ed53-484e-8c36-05b66b02a6c3",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "a415d12f-777f-42dd-b7a6-750fdc0b7e08",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "e4a5f243-c077-4a3d-94e3-bf8d2b9a762b",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "32f68203-fc45-417c-be64-f5fa46fd165e",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "ed02b364-b80b-46fd-8e4b-cc2cf4a66f00",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_5ab60a62-9f17-4e40-a620-8b2d85712185",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "ffb231da-d85f-4566-a1b9-581adcf562dc",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "e5aa1d6f-de79-446d-909e-9ab7bb1c3757"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "1505ff23-ab94-459c-a299-ad3ede5dda57"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "1be348ce-8369-445f-852b-839277fbc117"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "706c2add-b21a-4639-a0fb-b751a2d3585c"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_774bd4c9-8f83-4a3f-9b7f-3b1b1b93112d",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "ba6ac08e-7abd-4a7e-8445-fa3193dcde77",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "29d728ac-2467-4a81-a92e-51310360347c",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "ed10a77a-cd02-4fde-afa4-99e01e122422",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "3bc40f41-a8e2-4897-9cda-93a2e46486bb",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "75b49cc7-c65e-4c49-b7b9-2f7722f62335",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "109b48b9-f8aa-4e11-aef8-ee7dba5a3edb",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "67047c48-de06-4fd9-9dd2-6a16be478240",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "1e3b8c1e-2e3d-4455-949b-9cc863110789",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_774bd4c9-8f83-4a3f-9b7f-3b1b1b93112d",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('dim_constants_research'[LastUpdated])), 1, 1), Date(Year(MAX('dim_constants_research'[LastUpdated])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "4f15a0b3-ca71-40bb-9f49-65ffd0fac48d",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "92f3b762-16bf-44e3-9310-02e2166910cc"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "abded287-4df2-4430-bf9b-632c7aedc26c"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "2d820f68-adb3-4a54-a851-f366281cdecb"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "1db6e86b-437e-444d-8cc6-fc1eecdc0cdb"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "fact_all_permits",
        "description": [
          "Historical data taken from STAR (jobindsats.dk) of full time workers in Aarhus by residence permit",
          "Figures are from the first quarter of each year",
          "Source file: fact_all_permits.csv"
        ],
        "lineageTag": "b58b106c-9bf4-4c14-990f-22e70b7ada04",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "48207ffe-3d86-4876-b8f4-df47e6049f05",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Work permit 3rd country",
            "dataType": "int64",
            "sourceColumn": "Work permit 3rd country",
            "formatString": "0",
            "lineageTag": "b3dc0f13-1124-4ff1-9516-bdc64333418f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Work permit EU",
            "dataType": "int64",
            "sourceColumn": "Work permit EU",
            "formatString": "0",
            "lineageTag": "6b523645-bbee-45f1-8b36-ec63ebda0575",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Study permit",
            "dataType": "int64",
            "sourceColumn": "Study permit",
            "formatString": "0",
            "lineageTag": "44f8799b-e3fc-48d9-a7c0-d93d6695d9a1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Family reunification",
            "dataType": "int64",
            "sourceColumn": "Family reunification",
            "formatString": "0",
            "lineageTag": "a8806941-c6fe-4f41-a839-8a60c5805e11",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Permanent residency",
            "dataType": "int64",
            "sourceColumn": "Permanent residency",
            "formatString": "0",
            "lineageTag": "42c352bc-2997-40a1-a0a1-7c6cf1ed7249",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ukraine Emergency Law",
            "dataType": "int64",
            "sourceColumn": "Ukraine Emergency Law",
            "formatString": "0",
            "lineageTag": "b7252112-b92b-4199-80c0-fd5ad93e110f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_all_permits",
            "mode": "import",
            "queryGroup": "Fact tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\my power bi\\aarhus-retention-model\\data\\processed\\fact_all_permits.csv\"),[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Work permit 3rd country\", Int64.Type}, {\"Work permit EU\", Int64.Type}, {\"Study permit\", Int64.Type}, {\"Family reunification\", Int64.Type}, {\"Permanent residency\", Int64.Type}, {\"Ukraine Emergency Law\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_population",
        "description": [
          "Historical population of foreign citizens between the age of 20 and 64 in Aarhus ",
          "taken from FOLK1D on Statbank.dk",
          "Source file: fact_population.csv"
        ],
        "lineageTag": "85580609-5c88-4649-bfe5-084ab061d198",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "2f3b04bc-0370-453d-ae6b-ff27ac407a64",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Working age internationals",
            "dataType": "int64",
            "sourceColumn": "Working age internationals",
            "formatString": "0",
            "lineageTag": "649c41d5-71ad-4d96-a64f-746414eb0d33",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_population",
            "mode": "import",
            "queryGroup": "Fact tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\my power bi\\aarhus-retention-model\\data\\processed\\fact_population.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    // Removed null rows",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [Column1] <> null and [Column1] <> \"\"),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Filtered Rows\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\" \"\"Foreign citizens 20-64 years\"\"\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\" \"\"Foreign citizens 20-64 years\"\"\", \"Working age internationals\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_migration",
        "description": [
          "International inflow and outflow of foreign adults between the age of 20-64 ",
          "(for Aarhus)",
          "Taken from VAN1AAR and VAN2AAR from statbank.dk",
          "",
          "Source file: fact_migration.csv"
        ],
        "lineageTag": "5fffb4ae-e14a-4ea1-86bd-80cb661e2839",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "1018e5ca-8213-4cee-9faf-894160e27211",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Immigration foreign citizens 20-64 years",
            "dataType": "int64",
            "sourceColumn": "Immigration foreign citizens 20-64 years",
            "formatString": "0",
            "lineageTag": "5d40cfeb-cd5d-44c7-bd40-b2cb03526884",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Emigration foreign citizens 20-64 years",
            "dataType": "int64",
            "sourceColumn": "Emigration foreign citizens 20-64 years",
            "formatString": "0",
            "lineageTag": "1695fb5c-05a9-444d-bac6-107dfda8486d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_migration",
            "mode": "import",
            "queryGroup": "Fact tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\my power bi\\aarhus-retention-model\\data\\processed\\fact_migration.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Immigration foreign citizens 20-64 years\", Int64.Type}, {\"Emigration foreign citizens 20-64 years\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_forecast",
        "description": [
          "Projection of future trends using linear regression of historical data. Real-world events will likely cause significant deviations. ",
          "",
          "These are intended as a base-line not predictions",
          "",
          "Source file: forecast_reliability_assessment.csv"
        ],
        "lineageTag": "811b26d3-0a25-480c-a223-3ac7d63007cd",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "237c3c3a-4f21-402b-9101-5cb1e7150c72",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "b4ac99b0-1ed0-4e83-b9ef-4edfc25eed69",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Metric",
            "dataType": "string",
            "sourceColumn": "Metric",
            "lineageTag": "56e6c174-8eb6-45c3-879d-59d488b282a4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Forecast",
            "dataType": "int64",
            "sourceColumn": "Forecast",
            "formatString": "0",
            "lineageTag": "26dcd78d-92a4-4937-9a99-ac5f22d03515",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Uncertainty (±)",
            "dataType": "int64",
            "sourceColumn": "Uncertainty (±)",
            "formatString": "0",
            "lineageTag": "6855c06d-2bf0-45aa-8019-058fc59a3e51",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CV (%)",
            "dataType": "double",
            "sourceColumn": "CV (%)",
            "lineageTag": "580ce5f6-e79a-47ae-ad13-ebac8021bc34",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "R²",
            "dataType": "double",
            "sourceColumn": "R²",
            "lineageTag": "42085db8-75d7-4695-89dc-edff60de48e8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "MAPE (%)",
            "dataType": "double",
            "sourceColumn": "MAPE (%)",
            "lineageTag": "6b9a16b3-a0c1-4dc8-bc24-d16e8da45f7e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Uncertainty (%)",
            "dataType": "double",
            "sourceColumn": "Uncertainty (%)",
            "lineageTag": "525dc8fb-7d55-4db5-a27d-46b31a10801c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Reliability",
            "dataType": "string",
            "sourceColumn": "Reliability",
            "lineageTag": "a43928c5-a17f-4528-bfca-3c5e93e3ffc7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_forecast",
            "mode": "import",
            "queryGroup": "Fact tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\my power bi\\aarhus-retention-model\\outputs\\forecast_tables\\forecast_reliability_assessment.csv\"),[Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Category\", type text}, {\"Metric\", type text}, {\"Forecast\", Int64.Type}, {\"Uncertainty (±)\", Int64.Type}, {\"CV (%)\", type number}, {\"R²\", type number}, {\"MAPE (%)\", type number}, {\"Uncertainty (%)\", type number}, {\"Reliability\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_calendar",
        "lineageTag": "d5e1ca05-9083-4542-852d-8f8a27f5ddef",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "fcaa8162-647b-413f-952d-2432d2be470a",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "442c1285-746e-4f5f-88d1-3503d1969983",
                "defaultHierarchy": {
                  "table": "LocalDateTable_a1b0083e-86ca-4773-9255-be49dcd41844",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "f98a9a9f-0c08-4a1b-a01c-f28cb19c3142",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "lineageTag": "0d32b716-1b41-4cc2-8de4-df7e687def73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_calendar",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMtQ31DcyMDJU0lECIo/M4pL8oszkxBylWB24pBE+SWN8kib4JE3xSZpBJAOK8rNSk0tSU5DlzPHIWeCRs8QtZ2yAIRcLAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, Year = _t, Type = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}, {\"Year\", type text}, {\"Type\", type text}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year.1\", each Date.Year([Date]), Int64.Type),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Inserted Year\",{\"Year\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"Date\", \"Year.1\", \"Type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Year.1\", \"Year\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_a1b0083e-86ca-4773-9255-be49dcd41844",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "f0163696-dcf2-454a-b260-46d0918b3a74",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "b32afc23-28be-4ba9-acf5-4e3f7b8218b5",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "9648a04d-79a9-4d0a-a9d6-74462d4ceefe",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "349bad43-4473-4aa0-a4e7-5055677132f4",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "d88479ac-6223-4234-9897-9d01a987624b",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "bb735481-25f4-4522-9595-7d57f5f9e3a6",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "3713bad6-3ab5-45c4-8b30-c4db725e684d",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "ec3afdd2-6bcd-41fb-94e3-f8e435dcf80a",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_a1b0083e-86ca-4773-9255-be49dcd41844",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('dim_calendar'[Date])), 1, 1), Date(Year(MAX('dim_calendar'[Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "2c9071a7-41fd-430a-badf-2c428eca7a4e",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "d8de4c43-48ea-4788-9284-fd28232107fb"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "4a08ee54-9fc3-4e58-aad8-f39708ac5018"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "079d05a3-bdc7-45f7-8552-04888c81dfe0"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "1447606f-5052-4c76-a5d4-0045a74cbe9e"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Measures Folder",
        "lineageTag": "3b36f6ea-e185-4e0c-a5ca-1daf1a51ed40",
        "columns": [
          {
            "name": "_Measures",
            "dataType": "string",
            "sourceColumn": "_Measures",
            "lineageTag": "fc017973-309c-4a7f-88dd-d1d3c46968fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Measures Folder",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCkgsKlHwz0tVio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Measures \" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Measures \", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Measures \", \"_Measures\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Net Migration",
            "description": [
              "Immigration - emigration",
              ""
            ],
            "expression": [
              "",
              "SUM(fact_migration[Immigration foreign citizens 20-64 years]) - SUM(fact_migration[Emigration foreign citizens 20-64 years])"
            ],
            "formatString": "0",
            "displayFolder": "Simple metrics",
            "lineageTag": "77ab8e1d-26aa-4567-be6e-7af2726ae1df"
          },
          {
            "name": "Total with Work Permits",
            "description": "Sum of ft workers with work permits",
            "expression": [
              "",
              "SUM(fact_all_permits[Work permit 3rd country]) + SUM(fact_all_permits[Work permit EU])"
            ],
            "formatString": "0",
            "displayFolder": "Simple metrics",
            "lineageTag": "de803e9d-12c8-4be0-8a9e-610a83677974"
          },
          {
            "name": "Total Full Time Foreign Workforce",
            "description": "Sum of all ft workers with all residence permit types",
            "expression": [
              "",
              "SUM(fact_all_permits[Work permit 3rd country]) + ",
              "SUM(fact_all_permits[Work permit EU]) + ",
              "SUM(fact_all_permits[Family reunification]) +",
              "SUM(fact_all_permits[Permanent residency])+",
              "SUM(fact_all_permits[Ukraine Emergency Law]) +",
              "SUM(fact_all_permits[Study permit])"
            ],
            "formatString": "0",
            "displayFolder": "Simple metrics",
            "lineageTag": "636cc1a3-d664-4282-a85e-8a1b9e1fd98c"
          },
          {
            "name": "Selected percentage With Working Accompanying Partner",
            "description": "Calculating the value of full time employed accompanying partners from user input",
            "expression": [
              "",
              "",
              "VAR work_Partner = SELECTEDVALUE(",
              "    'param_% Employment of Accompanying Partner'[Value]",
              ")",
              "",
              "RETURN",
              "work_Partner"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "1217e59d-5449-4b02-83f5-0482f89965dc"
          },
          {
            "name": "Current Percentage of single workers with work permits",
            "description": [
              "Estimating the percentage of full time workers with work permits who are not married (or married to a local)",
              ""
            ],
            "expression": [
              "// if we know x % have partners, then  1-x is single",
              "VAR coupled = [Current percentage with a partner]",
              "",
              "RETURN",
              "(1-coupled)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from constants",
            "lineageTag": "763a0d08-fc20-4c42-8f1d-4aabb3da48da"
          },
          {
            "name": "Current Percentage With working Accompanying Partner",
            "description": "From research, how many primary workers have an employed partner (including part time)",
            "expression": [
              "// of the accompanying partners, how many have any kind of job?",
              "",
              "//1-[Current Percentage With Unemployed Accompanying Partner]"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from constants",
            "lineageTag": "9cad096d-de4d-4829-b649-710561cab927"
          },
          {
            "name": "Current percentage with an accompanying partner",
            "expression": [
              "// finding the subset of \"accompanying partners\" (as in a partner brought",
              "                                                    // with the worker, as opposed to one met here)",
              "",
              "VAR accompany = LOOKUPVALUE(",
              "    dim_constants_research[Value], ",
              "    dim_constants_research[ConstantID], ",
              "    \"national_partners_accompanying_%\")",
              "RETURN",
              "[Current percentage with a partner]*accompany",
              ""
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "6d5f6875-c381-435a-a368-da36361e77dd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Current percentage with a Danish partner",
            "expression": [
              "",
              "VAR CouplePct = LOOKUPVALUE(",
              "    dim_constants_research[Value], ",
              "    dim_constants_research[ConstantID], ",
              "    \"national_worker_partners_%\") // how many have partners",
              "VAR danish = LOOKUPVALUE(",
              "    dim_constants_research[Value], ",
              "    dim_constants_research[ConstantID], ",
              "    \"national_partners_danish_%\") // how many of those partners are Danish",
              "RETURN",
              "CouplePct*danish",
              ""
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "e857ef0a-2f9c-4580-adf7-36440a1f65d0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selected percentage With unemployed or underemployed Accompanying Partner",
            "expression": [
              "",
              "",
              "VAR work_Partner = SELECTEDVALUE(",
              "    'param_% Employment of Accompanying Partner'[Value]",
              ")",
              "",
              "RETURN",
              "",
              "(1-work_Partner)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "fa48d848-102d-49a0-9e78-98a38f95700a"
          },
          {
            "name": "Current percentage with a partner",
            "expression": [
              "",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value], ",
              "    dim_constants_research[ConstantID], ",
              "    \"national_worker_partners_%\")",
              "",
              ""
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "e19a576e-e333-4e87-95df-0f40c420d795",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total with Work Permits (2025)",
            "expression": [
              "",
              "VAR SelectedYear = 2025",
              "RETURN",
              "",
              "CALCULATE(",
              "    SUM(fact_all_permits[Work permit 3rd country]) +",
              "    SUM(fact_all_permits[Work permit EU]),",
              "    fact_all_permits[Year] = SelectedYear",
              ")",
              ""
            ],
            "formatString": "0",
            "displayFolder": "Simple metrics",
            "lineageTag": "cd51c678-866e-4568-9d23-0a4aa1c83915"
          },
          {
            "name": "SegmentedCurrentEstimates",
            "expression": [
              "",
              "VAR SegmentCode = SELECTEDVALUE(dim_Segments[SegmentCode])",
              "VAR Base = [Total with Work Permits (2025)]  ",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SegmentCode = \"no_partner\", Base * [Current Percentage of single workers with work permits],",
              "    SegmentCode = \"danish_partner\", Base * [Current percentage with a Danish partner],",
              "    SegmentCode = \"partner\", Base * [Current percentage with an accompanying partner],",
              "    BLANK()",
              ")",
              ""
            ],
            "formatString": "0",
            "displayFolder": "Segmented",
            "lineageTag": "7f8637cd-d658-4225-a55e-016cdbfd5091"
          },
          {
            "name": "Current Percentage With Unemployed Accompanying Partner",
            "expression": [
              "// of the accompanying partners, how many are unemployed?",
              "// [Current percentage with an accompanying partner] * [SpouseUnemploymentRate]"
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "bb3847f4-d39b-4679-b61d-fd6f0fb75eed",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "SegmentedProjection",
            "expression": [
              "",
              "VAR SegmentCode = SELECTEDVALUE(dim_Segments[SegmentCode])",
              "VAR Base = [Total with Work Permits (2025)]  ",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SegmentCode = \"no_partner\", Base * [Current Percentage of single workers with work permits],",
              "    SegmentCode = \"danish_partner\", Base * [Current percentage with a Danish partner],",
              "    SegmentCode = \"couples\", Base * [Selected percentage With Working Accompanying Partner],",
              "    SegmentCode = \"unemployed_partner\", Base * [Selected percentage With unemployed or underemployed Accompanying Partner],",
              "    BLANK()",
              ")",
              ""
            ],
            "displayFolder": "Segmented",
            "lineageTag": "9cf55836-f03e-419c-ad2d-c6a6e3289441",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Current Percentage of full time working partners",
            "expression": [
              "// of the workers with an accompanying spouse, what percentage have full time work?",
              "",
              "VAR ft = LOOKUPVALUE(",
              "    dim_constants_research[Value], ",
              "    dim_constants_research[ConstantID], ",
              "    \"CPH_partners_fulltime_%\" ) //would gladly update this for local circumstances",
              "VAR unemployed = LOOKUPVALUE(",
              "    dim_constants_research[Value], ",
              "    dim_constants_research[ConstantID], ",
              "    \"CPH_partners_unemployed_%\" ) //again, I wish I knew the local percentage",
              "",
              "",
              "RETURN",
              "ft * (1-unemployed)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from constants",
            "lineageTag": "9ab51a0c-1658-4a03-b18c-f142723f4f45"
          },
          {
            "name": "Estimate of Number of Un and Underemployed Partners",
            "expression": [
              "",
              "",
              "VAR EmploymentRate = [Under and Unemployed Spouse Share]",
              "",
              "RETURN",
              "[Current Estimate of Workers with an accompanying partner (2025)] * EmploymentRate",
              ""
            ],
            "formatString": "0",
            "displayFolder": "Segmented",
            "lineageTag": "a4745660-46c7-4c57-9514-7adae35ac5b7"
          },
          {
            "name": "SpouseEmploymentRate",
            "expression": [
              "//also has been improving in CPH, no idea if this is a national trend",
              "VAR unemployed = LOOKUPVALUE(",
              "    dim_constants_research[Value],dim_constants_research[ConstantID],\"CPH_partners_unemployed_%\")",
              "RETURN ",
              "1-unemployed"
            ],
            "displayFolder": "Rates and Shares",
            "lineageTag": "e715da1e-e45d-445f-a57c-0d52570f0f8f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Spouse FullTime Rate",
            "expression": [
              "//CPH number, it has been increasing over time. No idea how it is in Aarhus",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID], ",
              "    \"CPH_partners_fulltime_%\")",
              ""
            ],
            "displayFolder": "Rates and Shares",
            "lineageTag": "c8eb21b2-d614-4503-825b-041b2f43699b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "SpouseUnemploymentRate",
            "expression": [
              "// Has been decreasing but might be local",
              "VAR unemployed = LOOKUPVALUE(",
              "    dim_constants_research[Value],dim_constants_research[ConstantID],\"CPH_partners_unemployed_%\")",
              "RETURN ",
              "unemployed"
            ],
            "displayFolder": "Rates and Shares",
            "lineageTag": "02be9e1a-b968-45ea-b714-8a642d867ec1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Potential Number of Un and Underemployed Partners",
            "expression": [
              "",
              "VAR TotalWorkers = [Current Estimate of Workers with an accompanying partner (2025)]",
              "VAR EmploymentRate = [Selected percentage With unemployed or underemployed Accompanying Partner]",
              "",
              "RETURN",
              "TotalWorkers * EmploymentRate"
            ],
            "formatString": "0",
            "displayFolder": "Segmented",
            "lineageTag": "21f46ed7-e974-4d59-9468-2594427e1cb9"
          },
          {
            "name": "Under and Unemployed Spouse Share",
            "expression": [
              "",
              "[Underemployed Share] + [SpouseUnemploymentRate]",
              ""
            ],
            "displayFolder": "Rates and Shares",
            "lineageTag": "28b5e7ae-3e1b-4ed5-97a0-cf13acb46b2a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Underemployed Share",
            "expression": [
              "// Maybe some spouses do not want to work more than 30 hours but I do not have data on that.",
              "[SpouseEmploymentRate] * (1 - [Spouse FullTime Rate])",
              ""
            ],
            "displayFolder": "Rates and Shares",
            "lineageTag": "329f92ba-7e49-462f-81c9-07fb73fe28c8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Narrative Page 1 Part 1",
            "expression": [
              "",
              "\"In 2022, only about 44% of accompanying spouses in Copenhagen found full-time work within a year.\" & ",
              "UNICHAR(10) & ",
              "\"If Aarhus follows the same pattern, around \" & ",
              "ROUND([Estimate of Number of Un and Underemployed Partners] , -2) & ",
              "\" potential workers are under or unemployed.\" & ",
              "UNICHAR(10) & ",
              "\"Use the selector above to see how many extra workers Aarhus could gain without recruiting more from abroad.\"",
              ""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "6311782d-1f42-4f9b-b686-2ef886618107"
          },
          {
            "name": "Extra Workers at Selected Employment Rate",
            "expression": [
              "",
              "ROUND(",
              "[Current Estimate of Workers with an accompanying partner (2025)] * [Selected percentage With Working Accompanying Partner],-2) //nearest hundred"
            ],
            "formatString": "0",
            "displayFolder": "Measures from slicers",
            "lineageTag": "db8f4914-1da0-4106-b815-af9e924ace25"
          },
          {
            "name": "Current Estimate of Workers with an accompanying partner (2025)",
            "expression": [
              "",
              "ROUND(",
              "[Total with Work Permits (2025)]* [Current percentage with an accompanying partner],-2) //round to nearest 100"
            ],
            "formatString": "0",
            "displayFolder": "Segmented",
            "lineageTag": "fc459c39-7b7c-4e7c-b906-a2e5afa6715f"
          },
          {
            "name": "Total Work Permits Forecast",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fact_forecast[Forecast]),",
              "    fact_forecast[Metric] IN {\"Work permit 3rd country\", \"Work permit EU\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Simple Metrics",
            "lineageTag": "99ced4b3-39b0-4109-b2d8-9e8ee3020ad1"
          },
          {
            "name": "Work Permits Uncertainty Positive",
            "expression": [
              "//generated in Python",
              "VAR uncertainty=",
              "CALCULATE(",
              "    SUM(fact_forecast[Uncertainty (±)]),",
              "    fact_forecast[Metric] IN {\"Work permit 3rd country\", \"Work permit EU\"}",
              ")",
              "RETURN",
              "uncertainty"
            ],
            "formatString": "0",
            "displayFolder": "Graphing",
            "lineageTag": "8d6b496c-7083-4305-b137-edd5159e0c39"
          },
          {
            "name": "Net migration Uncertainty Negative",
            "expression": [
              "//generated these in Python",
              "VAR uncertainty =",
              "CALCULATE(",
              "    SUM(fact_forecast[Uncertainty (±)]),",
              "    fact_forecast[Metric] IN {\"Net migration\"}",
              ")",
              "RETURN",
              "-uncertainty"
            ],
            "formatString": "0",
            "displayFolder": "Graphing",
            "lineageTag": "a0573f15-dc73-4104-8ceb-2700845ef016"
          },
          {
            "name": "Target Line Workers",
            "expression": [
              "// if we start at 6345 and increase by 1500. We are already a bit behind because it was ",
              "                        //supposed to be 1500 extra starting this year. Plus Aarhus counted all the other foreign workers like permanent residency, ",
              "                        // family reunification etc but I think if we want to see an increase, this group is most important",
              "VAR Baseline2025 = 6345  ",
              "VAR CurrentYear = SELECTEDVALUE(dim_calendar[Year])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        CurrentYear = 2025, [Total with Work Permits],",
              "        CurrentYear >= 2026 && CurrentYear <= 2030, Baseline2025 + ((CurrentYear - 2025) * 1500),",
              "        BLANK()",
              "    )"
            ],
            "formatString": "0",
            "displayFolder": "Graphing",
            "lineageTag": "f5d47f3f-9c1b-4db7-9672-44c564687aa5"
          },
          {
            "name": "Total Net Migration Forecast",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fact_forecast[Forecast]),",
              "    fact_forecast[Metric] IN {\"Net migration\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Simple metrics",
            "lineageTag": "eb2878cb-a49b-42b5-9ff4-88e47fd74452"
          },
          {
            "name": "Work Permits Uncertainty Negative",
            "expression": [
              "//generated in Python",
              "VAR uncertainty=",
              "CALCULATE(",
              "    SUM(fact_forecast[Uncertainty (±)]),",
              "    fact_forecast[Metric] IN {\"Work permit 3rd country\", \"Work permit EU\"}",
              ")",
              "RETURN",
              "- uncertainty"
            ],
            "formatString": "0",
            "displayFolder": "Graphing",
            "lineageTag": "631935de-92e3-416b-af2f-11a22f767e5d"
          },
          {
            "name": "Net migration Uncertainty Positive",
            "expression": [
              "//generated these in Python",
              "VAR uncertainty =",
              "CALCULATE(",
              "    SUM(fact_forecast[Uncertainty (±)]),",
              "    fact_forecast[Metric] IN {\"Net migration\"}",
              ")",
              "RETURN",
              "uncertainty"
            ],
            "formatString": "0",
            "displayFolder": "Graphing",
            "lineageTag": "8f0b7a8b-b508-497f-8983-42ea0556ba14"
          },
          {
            "name": "Narrative Page 1 Part 2",
            "expression": [
              "",
              "VAR employedRate = [Selected percentage With Working Accompanying Partner]",
              "VAR employedPct = LOOKUPVALUE(dim_constants_research[Value], dim_constants_research[ConstantID], \"cph_employed_partner_five_year_%\")*100",
              "VAR unemployedPct = LOOKUPVALUE(dim_constants_research[Value], dim_constants_research[ConstantID], \"cph_unemployed_partner_five_year_%\")*100",
              "VAR retentionNone = FORMAT(ROUND([Retention All Unemployed Partners (2025-2030)], -2), \"0\")",
              "VAR partnerTotal = FORMAT(ROUND([Current Estimate of Workers with an accompanying partner (2025)], -2), \"0\")",
              "VAR retentionEmployed = FORMAT(ROUND([Retention Selected Value of Employed Partners (2025-2030)], -2)*2, \"0\")",
              "VAR retentionUnemployed = FORMAT(ROUND([Retention Selected Value of Unemployed Partners (2025-2030)], -2), \"0\")",
              "VAR totalRetention = FORMAT(ROUND([Retention Selected Total], -2), \"0\")",
              "",
              "RETURN",
              "\"From 2017, the five-year retention rate in Copenhagen was \" & ",
              "employedPct & \"% for workers with employed spouses, and \" & ",
              "unemployedPct & \"% for those whose partners weren't working.\" & UNICHAR(10) &",
              "\"If no partners work, only \" & retentionNone & \" out of \" & partnerTotal & \" households with couples are likely to stay.\" & UNICHAR(10) &",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    employedRate = 1,",
              "        \"If all partners work full-time, up to \" & totalRetention & \" workers might stay.\",",
              "    employedRate = 0,",
              "        \"\",  -- We already said \"If no partners work...\" above, so don’t repeat it",
              "    employedRate > 0 && employedRate < 1,",
              "        \"At the rate you chose above, \" & ",
              "        retentionEmployed & \" people in dual career couples might stay (since the partner counts as a worker too), until 2030.\" & UNICHAR(10) &",
              "        \"That's alongside \" & retentionUnemployed & ",
              "        \" retained workers whose partners aren’t employed.\" & UNICHAR(10) &",
              "        \"In total, that adds up to around \" & totalRetention & ",
              "        \" retained international workers of the cohort with partners in 2030.\",",
              "    \"\"  -- fallback",
              ") & UNICHAR(10) &",
              "\"(This model treats everyone as a new arrival, since we don’t have data on how long they’ve been in Denmark.)\"",
              ""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "00a720e7-536c-4f0b-a46a-3bcbe65ffd1a"
          },
          {
            "name": "Retention All Unemployed Partners (2025-2030)",
            "expression": [
              "// what if all the accompanying partners were unemployed?",
              "VAR unemployed_retention =",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"cph_unemployed_partner_five_year_%\")",
              "RETURN",
              "",
              "[Current Estimate of Workers with an accompanying partner (2025)]*unemployed_retention",
              ""
            ],
            "formatString": "0",
            "displayFolder": "Retention",
            "lineageTag": "d689d256-3d37-4605-9876-e7e4fd1f5132"
          },
          {
            "name": "Retention Selected Value of Employed Partners (2025-2030)",
            "expression": [
              "",
              "VAR employed_retention =",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"cph_employed_partner_five_year_%\")",
              "VAR employed =",
              "[Selected percentage With Working Accompanying Partner]",
              "VAR workers =",
              "[Current Estimate of Workers with an accompanying partner (2025)]",
              "",
              "RETURN",
              "employed_retention*employed*workers"
            ],
            "formatString": "0",
            "displayFolder": "Measures from slicers",
            "lineageTag": "ab455e4c-6163-41b6-add8-e641e0ca7fdd"
          },
          {
            "name": "Retention Selected Value of Unemployed Partners (2025-2030)",
            "expression": [
              "",
              "VAR unemployed_retention =",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"cph_unemployed_partner_five_year_%\")",
              "",
              "RETURN",
              "[Current Estimate of Workers with an accompanying partner (2025)]*[Selected percentage With unemployed or underemployed Accompanying Partner]*unemployed_retention"
            ],
            "formatString": "0",
            "displayFolder": "Measures from slicers",
            "lineageTag": "3f9a9589-e13b-4450-b7fa-1ea262098434"
          },
          {
            "name": "Retention Selected Total",
            "expression": [
              "",
              "VAR dual_career =",
              "2*[Retention Selected Value of Employed Partners (2025-2030)] // because it is two for the price of one, my friends",
              "",
              "RETURN",
              "dual_career+[Retention Selected Value of Unemployed Partners (2025-2030)]"
            ],
            "formatString": "0",
            "displayFolder": "Measures from slicers",
            "lineageTag": "a9aedbc7-a85d-4057-a289-6986e785d842"
          },
          {
            "name": "Title Page 1",
            "expression": [
              "",
              "",
              "\"Aarhus Could Gain \" &",
              " FORMAT(ROUND([Extra Workers at Selected Employment Rate],0), \"0\") &",
              " \" Extra Workers Without Recruiting From Abroad\"",
              ""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "c4ed4b6b-b745-4f1b-9b49-861837eee08f"
          },
          {
            "name": "Selected Percentage Retained after Five Years (non accompanied partner segment)",
            "expression": [
              "",
              "[Selected average retention segment]*LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"national_retention_five_year_%\"",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "e286c7ba-e174-453a-864f-24003b951d79"
          },
          {
            "name": "Selected average retention segment",
            "expression": [
              "",
              "1 - [Selected Employed Segment] - [Selected Unemployed Segment]"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "700401e4-0bfa-4b0d-9042-2e759fa75da2"
          },
          {
            "name": "Selected Employed Segment",
            "expression": [
              "",
              "[Selected percentage With Working Accompanying Partner] * [Current percentage with an accompanying partner]"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "db7ea3c1-1039-4935-ac24-9a99ee87ab3a"
          },
          {
            "name": "Selected Unemployed Segment",
            "expression": [
              "",
              "[Selected percentage With unemployed or underemployed Accompanying Partner] * [Current percentage with an accompanying partner]"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "a2fff1ec-b585-4b78-b106-496899562d40"
          },
          {
            "name": "Potential Employed Segment",
            "expression": [
              "",
              "VAR retention_five_years =",
              "LOOKUPVALUE(dim_constants_research[Value],",
              "dim_constants_research[ConstantID],",
              "\"cph_employed_partner_five_year_%\")",
              "",
              "RETURN",
              "[Current percentage with an accompanying partner]*retention_five_years"
            ],
            "displayFolder": "Segmented",
            "lineageTag": "11b0e12e-ced3-45cb-8d76-924eb646fbac",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selected Percentage Retained after Five Years (Employed partner)",
            "expression": [
              "",
              "[Selected Employed Segment]*",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"cph_employed_partner_five_year_%\"",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "c4dd3d91-2e4e-4b27-a224-946a404863a7"
          },
          {
            "name": "Potential Unemployed Segment",
            "expression": [
              "",
              "VAR retention_five_years =",
              "LOOKUPVALUE(dim_constants_research[Value],",
              "dim_constants_research[ConstantID],",
              "\"cph_unemployed_partner_five_year_%\")",
              "",
              "RETURN",
              "[Current percentage with an accompanying partner]*retention_five_years"
            ],
            "displayFolder": "Segmented",
            "lineageTag": "b7979402-01ef-4800-a9ab-602c3e7f7678",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selected Percentage Retained after Five Years (Unemployed partner)",
            "expression": [
              "",
              "[Selected Unemployed Segment]*",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"cph_unemployed_partner_five_year_%\"",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Measures from slicers",
            "lineageTag": "ee2e327e-e72f-4d10-abcb-6cd459970b00"
          },
          {
            "name": "Dual partners households",
            "expression": [
              "",
              "//count for double the work force",
              "",
              "2* [Selected Percentage Retained after Five Years (Employed partner)]"
            ],
            "displayFolder": "Segmented",
            "lineageTag": "08c7f58d-2e84-4a5e-854a-2f78dbd14652",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Approximate recruitment of single workers per year needed to allow for five year retention",
            "expression": [
              "// This is a bit of a fudge because retention is better over shorter",
              "VAR simple_retention =                                                                        // time periods but since Aarhus wants to recruit and retain over 2025-2030",
              "                                                                                            // we will look at how many will remain after five years no matter when they",
              "LOOKUPVALUE(                                                                                // arrive",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"national_retention_five_year_%\")",
              "",
              "RETURN",
              "ROUND(",
              "    DIVIDE(",
              "        DIVIDE(",
              "            7500,",
              "            simple_retention ),",
              "            5) // 5 years",
              "            , -2) // rounding accuracy"
            ],
            "formatString": "0",
            "displayFolder": "Retention",
            "lineageTag": "67dc0a42-e896-4a1c-b881-c027900ef631"
          },
          {
            "name": "Recruitment of households needed to allow for five year retention per year",
            "expression": [
              "// Workers are divided into segments based on life circumstances",
              "VAR single_households =                                                      // and their retention rate calculated",
              "[Selected Percentage Retained after Five Years (non accompanied partner segment)]",
              "",
              "VAR unemployed_partner_households =",
              "[Selected Percentage Retained after Five Years (Unemployed partner)]",
              "",
              "VAR dual_careers =",
              "[Dual partners households]",
              "",
              "",
              "RETURN",
              "ROUND(",
              "    DIVIDE(",
              "        DIVIDE(",
              "            7500,",
              "            single_households + unemployed_partner_households + dual_careers ),",
              "            5), // 5 years",
              "            -2) // Rounding accuracy"
            ],
            "formatString": "0",
            "displayFolder": "Retention",
            "lineageTag": "22b2b852-6bc7-4a80-b0b9-ef274b87100d"
          },
          {
            "name": "Title Page 2",
            "expression": [
              "",
              "",
              "\"How Many New Households Does Aarhus Need to Recruit?\"",
              ""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "21f9f8c5-9b89-4540-b4f9-97d772920b2f"
          },
          {
            "name": "Narrative Page 2 Part 2",
            "expression": [
              "",
              "\"New households needed in the first year if \" &",
              "SELECTEDVALUE('param_% Employment of Accompanying Partner'[Value])*100 &",
              "\"% of the partners had full time jobs\""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "0688a555-1fa2-4bca-a335-4418846e91fd"
          },
          {
            "name": "Narrative Page 2 Part 1",
            "expression": [
              "",
              "\"New households needed in the first year if only single people were recruited\" "
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "99344617-8255-4fd5-a4ed-92823016af67"
          },
          {
            "name": "Footer",
            "expression": [
              "",
              "\"For illustrative purposes only.\"&",
              "UNICHAR(10)&",
              "\"Research, modelling and visuals by Kelly Rasmussen.\"&",
              "UNICHAR(10)&",
              "\"Last data refresh: \"&",
              "FORMAT(",
              "    DATEVALUE(",
              "        LOOKUPVALUE(",
              "            MetaData[Value],",
              "            MetaData[Field],",
              "            \"LastUpdated\")",
              "    ), ",
              "    \"MMMM yyyy\"",
              ")"
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "e7cfafc2-74b4-4b9d-930f-d5d59d096a99"
          },
          {
            "name": "Total Capacity",
            "expression": [
              "",
              "540 //hard coded and obtained from a couple of press releases (600 for the entire school, 60 for Early Years). I will update this if I get better information",
              ""
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "1c230fc7-d6e8-4733-bf94-6a0759aed064"
          },
          {
            "name": "Current Number of students (October 2024)",
            "expression": [
              "",
              "SUM(fact_ais_2024[Internationals]) + ",
              "SUM(fact_ais_2024[Locals])"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "5de6bd05-636f-4ab4-89dd-b87e7fb28907"
          },
          {
            "name": "Places Available this year",
            "expression": [
              "",
              "[Total Capacity]-[Current Number of students (October 2024)]"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "197b4da3-e106-4d35-85ff-c628d88a3104"
          },
          {
            "name": "Percentage of international families that choose private schools",
            "expression": [
              "// this is Copenhagen data, would like to update. ",
              "                                                                    //Applies to new families",
              "LOOKUPVALUE(dim_constants_research[Value],",
              "dim_constants_research[ConstantID],",
              "\"private_school\")"
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "72433e7f-3a96-45de-a4f6-c642b4e259c2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Percentage of international workers that bring school age children",
            "expression": [
              "// this is national data",
              "VAR accompanying_children =",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"accompanying_children\"",
              ")",
              "VAR school_age =",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"school_age\"",
              ")",
              "",
              "RETURN",
              "accompanying_children*school_age",
              ""
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "1b8d080f-d684-434c-be2c-a3184ff1556d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Average number of children brought by internationals",
            "expression": [
              "// number found by inference, would like more research to confirm.",
              "LOOKUPVALUE(",
              "    dim_constants_research[Value],",
              "    dim_constants_research[ConstantID],",
              "    \"children_per_family\"",
              ")"
            ],
            "displayFolder": "Measures from constants",
            "lineageTag": "ff552a0f-862b-40b5-8f33-87d907d98727",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Potential New Students",
            "expression": [
              "",
              "Selectedvalue(",
              "    Dim_Param_Recruitment[Value])",
              "    *[Percentage of international families that choose private schools]",
              "    *[Percentage of international workers that bring school age children]",
              "    *[Average number of children brought by internationals]"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "8f3754f5-13dc-45c1-a232-88e2555a2121"
          },
          {
            "name": "Spare capacity in 2024_5",
            "expression": [
              "",
              "SUM(fact_ais_2024[Capacity])-[Current Number of students (October 2024)]"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "6a68a360-e11d-4401-b2e5-220fee61acac"
          },
          {
            "name": "Potential New Students per class",
            "expression": [
              "",
              "DIVIDE(",
              "[Potential New Students],",
              "10)"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "8d3ee4db-5a55-4f9f-8090-9f81b748b6e2"
          },
          {
            "name": "Years Until Classes Full",
            "expression": [
              "",
              "VAR SpareCapacity = [Spare capacity in 2024_5]",
              "VAR NewKidsPerYear = [Potential New Students per class]",
              "VAR YearsToFill = DIVIDE(SpareCapacity, NewKidsPerYear, 999)",
              "VAR YearsToGraduation = ",
              "    SWITCH(",
              "        SELECTEDVALUE(fact_ais_2024[Grade]),",
              "        \"MYP 5\", 0,  // They graduate this year",
              "        \"MYP 4\", 1,",
              "        \"MYP 3\", 2,",
              "        \"MYP 2\", 3,",
              "        \"MYP 1\", 4,",
              "        \"PYP 8\", 5,",
              "        \"PYP 7\", 6,",
              "        \"PYP 6\", 7,",
              "        \"PYP 5\", 8,",
              "        \"PYP 4\", 9,  // 9 years until graduation",
              "        99  // Safety default",
              "    )",
              "RETURN",
              "IF(YearsToFill > YearsToGraduation, BLANK(), YearsToFill)"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "ea0b91cd-ce19-4758-8ee1-1cb42d59aed0"
          },
          {
            "name": "Title page 3",
            "expression": [
              "",
              "\"If Aarhus Recruited \" &",
              "(ROUND([Recruitment of households needed to allow for five year retention per year],-2)) &",
              "\" Households Annually When Would AIS Reach Capacity?\""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "7819219e-da54-42c3-8527-553cd79c4c1c"
          },
          {
            "name": "Tooltip",
            "expression": [
              "",
              "",
              "\"Nearly half the oldest AIS middle school classes are local Danish students.",
              "As space tightens, it may be time to offer English-language instruction in some folkeskoler for older students to cater for this market without displacing internationals. \""
            ],
            "displayFolder": "Text Measures",
            "lineageTag": "d02dc72a-3fad-4748-a931-6559d4e596cc"
          },
          {
            "name": "Capacity Status",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK([Years Until Classes Full]), \"✅ Class will graduate first\",",
              "    [Years Until Classes Full] < 1, \"🔴 August 2025\",",
              "    [Years Until Classes Full] < 2, \"🔴 August 2026\", ",
              "    [Years Until Classes Full] < 3, \"🟠 August 2027\",",
              "    [Years Until Classes Full] < 4, \"🟠 August 2028\",",
              "    [Years Until Classes Full] < 5, \"🟡 August 2029\",",
              "    [Years Until Classes Full] < 6, \"🟡 August 2030\",",
              "    [Years Until Classes Full] < 7, \"🟢 After 2030\"",
              "    ",
              ")"
            ],
            "displayFolder": "Schools",
            "lineageTag": "91ed731a-d114-47e4-ad88-1b153ac129ae"
          },
          {
            "name": "Years until school full",
            "expression": [
              "",
              "IF(",
              "    [Potential New Students] - 60 <= 0,",
              "    BLANK(),",
              "    DIVIDE(",
              "        [Spare capacity in 2024_5],",
              "        [Potential New Students] - 60",
              "    )",
              ")//modelling outflow as 60 students per year to account for graduation and students moving school before graduation"
            ],
            "formatString": "0",
            "displayFolder": "Schools",
            "lineageTag": "b8bfcb8a-24fd-4442-9f9b-1bc9c1754849"
          },
          {
            "name": "Crunch School Year",
            "expression": [
              "",
              "IF(",
              "    ISBLANK([Years until school full]),",
              "    \"There will be space in some classes but keep an eye on individual year groups\",",
              "    IF(",
              "        2024 + [Years until school full] >= 2025 && 2024 + [Years until school full] <= 2030,",
              "        \"Recruitment may create capacity problems in \"&ROUND(2024+[Years until school full],0),",
              "        \"There will be space in some classes but keep an eye on individual year groups\"",
              "    )",
              ")"
            ],
            "lineageTag": "46cbcfad-4b91-4de5-9df2-a5e937c04c72"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "param_% Employment of Accompanying Partner",
        "lineageTag": "19536387-c052-413f-842a-f58ceb5c0e87",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "lineageTag": "1ee0bbdd-41ed-473a-a93d-3f0134391b68",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Label",
            "dataType": "string",
            "isNameInferred": true,
            "sourceColumn": "[Label]",
            "lineageTag": "4b1c9faf-eb34-4abf-b13a-1741daf1440a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "param_% Employment of Accompanying Partner",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    GENERATESERIES(0,1,0.1),",
                "    \"Label\", Format([Value], \"Percent\")",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0bafdb3c385f4ce3b56cdd465b766d51"
          }
        ]
      },
      {
        "name": "Dim_Param_Employed_partner",
        "lineageTag": "b8357c4d-7780-418d-b321-d598e60c6b9b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "lineageTag": "9e2c6083-4260-4f7e-80ae-7b9cbd651fdb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Label",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Label]",
            "sortByColumn": "SortOrder",
            "lineageTag": "cefebc7a-ae4e-4097-8c1c-474276f01d65",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortOrder",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortOrder]",
            "lineageTag": "e2f327a8-c6cc-4465-b5be-3c35307a4eb0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Param_Employed_partner",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    SELECTCOLUMNS(",
                "        'param_% Employment of Accompanying Partner',",
                "        \"Value\", [Value]",
                "    ),",
                "    \"Label\", FORMAT([Value] *100, \"0\") & \"% of partners work fulltime\",",
                "    \"SortOrder\", [Value]",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1c92dab06bd448b9945fb6bb524a53f8"
          }
        ]
      },
      {
        "name": "dim_Segments",
        "description": "generated",
        "lineageTag": "8bb8eb65-6b3a-4d80-a5dd-0fadf2b4acf2",
        "columns": [
          {
            "name": "SegmentLabel",
            "dataType": "string",
            "sourceColumn": "SegmentLabel",
            "lineageTag": "bc42d539-1332-4fe3-a17b-1f46fc51500d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SegmentCode",
            "dataType": "string",
            "sourceColumn": "SegmentCode",
            "lineageTag": "0d2e7be7-7e3e-4cbe-94aa-b33fecc94971",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_Segments",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dY9BCoMwEEWvMmTtLeoNuugiSBniUINxJkwM4u0bFNuI7fbNfw/GWvMQHUlh8fMALbJPA0TUmUlNY/oNPA/QNdbcPb8CwbJpZcJyOtc5mmKQlfoqeKC/TuYf1heevDZjgBsqFXlvpDJ2kmOgdCkjAzonU0Reyw9V/tPs3g==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SegmentLabel = _t, SegmentCode = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SegmentLabel\", type text}, {\"SegmentCode\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "MetaData",
        "lineageTag": "2b9b2c80-c949-4dae-acb0-ce85f5675db9",
        "columns": [
          {
            "name": "Field",
            "dataType": "string",
            "sourceColumn": "Field",
            "lineageTag": "39295aab-6047-4ca3-90a3-36f8d65ff39b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "lineageTag": "9f217326-81b2-4a4d-a02a-981943dbf9d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "MetaData",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Create the metadata table with all required fields",
                "    Source = Table.FromRows({",
                "        {\"1.0\", \"Aarhus International Workforce Forecast Model\"},",
                "        {\"STAR (jobindsats.dk), Statistics Denmark (Statbank.dk), København Kommune\", \"\"},",
                "        {\"This model forecasts international workforce trends in Aarhus Kommune through 2030 and analyzes spouse employment scenarios\", \"\"},",
                "        {\"Copenhagen partner employment and retention rates applied to Aarhus context. Linear trend forecasting for baseline projections. Fixed household composition ratios.\", \"\"},",
                "        {\"International workforce forecasting for Aarhus Kommune 2026-2030. Spouse employment scenario modeling. Excludes university student retention (out of scope).\", \"\"},",
                "        {\"Kelly Rasmussen\", \"\"}",
                "    }, type table [Value = text, Field = text]),",
                "    ",
                "    // Add the field names",
                "    #\"Added Index\" = Table.AddIndexColumn(Source, \"Index\", 0, 1),",
                "    #\"Added Field Names\" = Table.AddColumn(#\"Added Index\", \"MetadataField\", each ",
                "        if [Index] = 0 then \"DataVersion\"",
                "        else if [Index] = 1 then \"DataSource\" ",
                "        else if [Index] = 2 then \"Notes\"",
                "        else if [Index] = 3 then \"Assumptions\"",
                "        else if [Index] = 4 then \"AnalysisScope\"",
                "        else if [Index] = 5 then \"Author\"",
                "        else \"Unknown\"),",
                "    ",
                "    // Restructure to proper metadata format",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Field Names\",{\"Index\", \"Field\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"MetadataField\", \"Field\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Field\", \"Value\"}),",
                "    ",
                "    // Add LastUpdated as a separate row with current timestamp",
                "    #\"Added LastUpdated\" = Table.InsertRows(#\"Reordered Columns\", Table.RowCount(#\"Reordered Columns\"), {[Field = \"LastUpdated\", Value = DateTime.ToText(DateTime.LocalNow(), \"yyyy-MM-dd HH:mm:ss\")]}),",
                "    ",
                "    // Set proper data types",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added LastUpdated\",{{\"Field\", type text}, {\"Value\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_ais_2024",
        "description": [
          "Source: StatBank",
          "statbank.dk/INST10"
        ],
        "lineageTag": "4b732a8e-10ca-4f8a-931f-09da994f7f84",
        "columns": [
          {
            "name": "Grade",
            "dataType": "string",
            "sourceColumn": "Grade",
            "sortByColumn": "Sort Order",
            "lineageTag": "35b2731b-e1b8-4aa8-ad4b-83f194135fd4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Internationals",
            "dataType": "int64",
            "sourceColumn": "Internationals",
            "formatString": "0",
            "lineageTag": "1dc10e01-f27f-4b2d-84c0-be03b2842fac",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Locals",
            "dataType": "int64",
            "sourceColumn": "Locals",
            "formatString": "0",
            "lineageTag": "1dacf27f-93e9-41ca-9e41-3854fd37e36d",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Capacity",
            "dataType": "int64",
            "sourceColumn": "Capacity",
            "formatString": "0",
            "lineageTag": "360a47b3-c49d-41d6-b8c3-c28c0898db17",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sort Order",
            "dataType": "int64",
            "sourceColumn": "Sort Order",
            "formatString": "0",
            "lineageTag": "e6e3c688-abe2-48b3-b0d5-ae4b3526cba3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_ais_2024",
            "mode": "import",
            "queryGroup": "Fact tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\my power bi\\aarhus-retention-model\\data\\processed\\fact_ais_2024.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Grade\", type text}, {\"Persons of Danish origin\", Int64.Type}, {\"Immigrants\", Int64.Type}, {\"Descendant\", Int64.Type}, {\"Capacity\", Int64.Type}}),",
                "    // These are local children",
                "    #\"Summed Danes and Descendants\" = Table.AddColumn(#\"Changed Type\", \"Locals\", each [Persons of Danish origin]+[Descendant]),",
                "    #\"Changed Immigrants to Internationals\" = Table.RenameColumns(#\"Summed Danes and Descendants\",{{\"Immigrants\", \"Internationals\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Immigrants to Internationals\",{\"Grade\", \"Internationals\", \"Locals\", \"Capacity\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Other Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Sort Order\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "param Recruitment of International Workers",
        "lineageTag": "506d1d06-511a-416e-8c21-c615b01b42ea",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "98da7536-5f35-4d08-a82e-5f6fb106b9c4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Label",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Label]",
            "lineageTag": "1b036fe8-c73d-4c89-9050-edfb18add4c7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "param Recruitment of International Workers",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    GENERATESERIES(500,3200,100),",
                "    \"Label\", Format([Value], \"0\")",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c5abd07ccb1148dfa5ce477fb4ddb15b"
          }
        ]
      },
      {
        "name": "Dim_Param_Recruitment",
        "lineageTag": "9fbbd739-5b73-406a-9a08-4bfe0bed3dbe",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "abe9390a-ca6d-4283-a557-1ade0ef6db4a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Label",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Label]",
            "sortByColumn": "SortOrder",
            "lineageTag": "5b987b15-9e99-430d-98b4-c43f5fdf5eeb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortOrder",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortOrder]",
            "formatString": "0",
            "lineageTag": "91e4d3fe-2ecf-4b9d-8448-c171bc96a4a8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Param_Recruitment",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    SELECTCOLUMNS(",
                "        'param Recruitment of International Workers',",
                "        \"Value\", [Value]",
                "    ),",
                "    \"Label\", FORMAT([Value], \"0\") & \" new international households\",",
                "    \"SortOrder\", [Value]",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ba66d879eb73425bad8807fc7a5433d8"
          }
        ]
      },
      {
        "name": "dim_classes",
        "lineageTag": "345e744b-e781-4324-bac6-3355c8093c8a",
        "columns": [
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "lineageTag": "0f1edf85-ab67-484b-9f01-08f38305a5d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_classes",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCogMUDBRitWBsEzhLDM4yxzOsgCzfIEsQzjLCM4yhrNM4CygebEA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Class = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Class\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "976085ed-132c-4001-b99f-2a20c9eee21d",
        "fromTable": "dim_constants_research",
        "fromColumn": "LastUpdated",
        "toTable": "LocalDateTable_774bd4c9-8f83-4a3f-9b7f-3b1b1b93112d",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "442c1285-746e-4f5f-88d1-3503d1969983",
        "fromTable": "dim_calendar",
        "fromColumn": "Date",
        "toTable": "LocalDateTable_a1b0083e-86ca-4773-9255-be49dcd41844",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "AutoDetected_4ae377ee-a024-4b2f-9ff3-97962db4d522",
        "fromCardinality": "one",
        "fromTable": "fact_population",
        "fromColumn": "Year",
        "toTable": "dim_calendar",
        "toColumn": "Year",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "AutoDetected_982a52a0-d162-4343-86df-969114cb564e",
        "fromTable": "fact_forecast",
        "fromColumn": "Year",
        "toTable": "dim_calendar",
        "toColumn": "Year"
      },
      {
        "name": "fc5e084c-661d-c161-3e54-691ad8b8d306",
        "fromTable": "dim_calendar",
        "fromColumn": "Year",
        "toTable": "fact_all_permits",
        "toColumn": "Year",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "dbd79881-c165-132e-501b-bc3cc21daff0",
        "fromTable": "fact_migration",
        "fromColumn": "Year",
        "toTable": "dim_calendar",
        "toColumn": "Year",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "0fc72a56-97ae-0707-5336-717404e1a2df",
        "fromCardinality": "one",
        "fromTable": "Dim_Param_Employed_partner",
        "fromColumn": "Value",
        "toTable": "param_% Employment of Accompanying Partner",
        "toColumn": "Value",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "90b0a651-be7b-2b53-67de-efd8672055d2",
        "fromCardinality": "one",
        "fromTable": "dim_classes",
        "fromColumn": "Class",
        "toTable": "fact_ais_2024",
        "toColumn": "Grade",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "queryGroups": [
      {
        "folder": "Dimension tables",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Fact tables",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Measures",
        "description": "Keeping measures together",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_Segments\",\"dim_constants_research\",\"fact_all_permits\",\"fact_population\",\"fact_migration\",\"fact_forecast\",\"dim_calendar\",\"fact_ais_2024\",\"Measures Folder\",\"MetaData\",\"dim_classes\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.143.1204.0 (25.05)+23c84aace645781dd62b8a26eb0418c7e6a84b72"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  }
}